"""Deep Ball trivia pool for Reads' shared arcade/strategy formats.

This module deliberately reuses the already-certified Director capability
adapters instead of inventing a second question engine. A Strategy Arcade
format should feel different because of its state machine, but its football
knowledge should still exploit the breadth of the Reads Engine.

The old shared pool was only three shallow categories (team record, Heisman
school, Super Bowl winner). This pool rotates across game context, boxscore,
PBP, rankings, awards, coaching, transfers, rivalries and stat leaders.

Every question is generated by the same registered adapter used by Creator/
public generation, preserving source/QA rules and answer safety.
"""
from __future__ import annotations

import hashlib

from tools.director_v02 import registry
from tools.quiz_export import engine as engine_bootstrap
from tools.director_v04.story_arcade_adapter import load_story_mcqs, to_deep_round

# (mechanic, domain, predicate, player-facing category, optional filters)
_DEEP_CAPABILITIES = (
    ("guess", "NFL_GAME_BOXSCORE", "HAD_MORE_YARDS", "NFL Box Score: Total Yards", {}),
    ("guess", "NFL_GAME_BOXSCORE", "HAD_MORE_SACKS", "NFL Box Score: Pass Rush", {}),
    ("guess", "NFL_GAME_BOXSCORE", "HAD_FEWER_TURNOVERS", "NFL Box Score: Turnover Battle", {}),
    ("guess", "NFL_GAME_BOXSCORE", "HAD_FEWER_PENALTIES", "NFL Box Score: Discipline", {}),
    ("guess", "CFB_GAME_BOXSCORE", "HAD_MORE_SACKS", "CFB Box Score: Pass Rush", {}),
    ("guess", "NFL_SEASON_STATS", "LED_LEAGUE_IN_STAT", "NFL Season Leaders", {}),
    ("guess", "CFB_SEASON_STATS", "LED_LEAGUE_IN_STAT", "CFB National Leaders", {}),
    ("guess", "CFB_RANKING", "RANKED_IN_POLL", "CFB Poll History", {}),
    ("guess", "CFB_RANKING", "RANKED_HIGHER", "CFB Ranking Battles", {}),
    ("guess", "CFB_UPSET", "RANKING_UPSET", "CFB Ranked Upsets", {"biggest_only": True}),
    ("guess", "NFL_AWARDS", "WON_AWARD", "NFL Awards", {}),
    ("guess", "NFL_COACHING", "COACHED_TEAM", "NFL Coaching History", {}),
    ("guess", "CFB_TRANSFER", "ATTENDED_COLLEGE", "CFB Transfer Trails", {}),
    ("guess", "CFB_RIVALRY_TRIVIA", "CORRECT_TRIVIA_ANSWER", "CFB Rivalry Deep Cuts", {"rivalry_only": True}),
    ("guess", "NFL_SCORING_PLAY", "FIRST_TOUCHDOWN_SCORER", "NFL First-TD Recall", {}),
    ("guess", "NFL_DEFENSIVE_EVENT", "RECORDED_SACK", "NFL Defensive Plays: Sacks", {}),
    ("guess", "NFL_DEFENSIVE_EVENT", "RECORDED_INTERCEPTION", "NFL Defensive Plays: Picks", {}),
    ("guess", "NFL_DEFENSIVE_EVENT", "FORCED_FUMBLE", "NFL Defensive Plays: Forced Fumbles", {}),
    ("guess", "NFL_DEFENSIVE_EVENT", "RECOVERED_FUMBLE", "NFL Defensive Plays: Recoveries", {}),
    ("guess", "NFL_DRIVE", "DRIVE_RESULT", "NFL Drive Outcomes", {}),
    ("guess", "CFB_STAT_COMPARISON", "RUSHING_COMPARISON", "CFB Game Stats: Rushing", {}),
    ("guess", "CFB_STAT_COMPARISON", "PASSING_COMPARISON", "CFB Game Stats: Passing", {}),
    ("guess", "CFB_STAT_COMPARISON", "RECEIVING_COMPARISON", "CFB Game Stats: Receiving", {}),
    ("guess", "NFL_GAME_LEADER", "RUSHING_LEADER", "NFL Game Leaders: Rushing", {}),
    ("guess", "NFL_GAME_LEADER", "PASSING_LEADER", "NFL Game Leaders: Passing", {}),
    ("guess", "NFL_GAME_LEADER", "RECEIVING_LEADER", "NFL Game Leaders: Receiving", {}),
    ("guess", "CFB_GAME_LEADER", "RUSHING_LEADER", "CFB Game Leaders: Rushing", {}),
    ("guess", "CFB_GAME_LEADER", "PASSING_LEADER", "CFB Game Leaders: Passing", {}),
    ("guess", "CFB_GAME_LEADER", "RECEIVING_LEADER", "CFB Game Leaders: Receiving", {}),
    ("guess", "CFB_THREE_CLUES_ONE_CHAMPION", "TEAM_SEASON_FROM_THREE_CLUES", "CFB Three-Clue Champions", {}),
    ("guess", "NFL_OFFENSE_COLLEGE_CURATED", "TEAM_OF_CURRENT_OFFENSE_BY_COLLEGE", "NFL Offense by College", {}),
    ("guess", "NFL_SB_CHAMPION_OFFENSE_COLLEGE", "TEAM_SEASON_OF_CHAMPIONSHIP_OFFENSE_BY_COLLEGE", "Super Bowl Offense by College", {}),
    ("guess", "CFB_FILL_THE_COLLEGES", "COLLEGE_OF_POSITION", "CFB Lineup College Fill", {}),
    ("guess", "CFB_WHO_CHANGED", "CHANGED_POSITION", "CFB Lineup Change Detection", {}),
    ("guess", "CFB_POSITION_TRAP", "SWAPPED_POSITION_PAIR", "CFB Position Trap", {}),
    ("guess", "CFB_DUPLICATE_COLLEGE_HUNT", "REPEATED_COLLEGE", "CFB Duplicate College Hunt", {}),
    ("guess", "CFB_ONE_SCHOOL_MISSING", "MISSING_COLLEGE", "CFB Missing College", {}),
    ("guess", "CROSS_LEAGUE_HONORS", "ALL_AMERICAN_TO_NFL_DRAFT_TEAM", "All-American to NFL Draft Team", {}),
)

# Category-level diversity matters more than repeatedly pulling the same boxscore
# family just because it has several predicates.
MIN_DISTINCT_CATEGORIES_FOR_12 = 8

def _bucket_for(domain: str) -> str:
    if domain in {
        "NFL_GAME_BOXSCORE", "CFB_GAME_BOXSCORE", "NFL_SCORING_PLAY",
        "NFL_DEFENSIVE_EVENT", "NFL_DRIVE", "CFB_STAT_COMPARISON",
        "NFL_GAME_LEADER", "CFB_GAME_LEADER",
    }:
        return "Game Day"
    if domain in {
        "CFB_RANKING", "CFB_UPSET", "CFB_TRANSFER", "CFB_RIVALRY_TRIVIA",
        "CFB_THREE_CLUES_ONE_CHAMPION", "CFB_FILL_THE_COLLEGES",
        "CFB_WHO_CHANGED", "CFB_POSITION_TRAP", "CFB_DUPLICATE_COLLEGE_HUNT",
        "CFB_ONE_SCHOOL_MISSING",
    }:
        return "College Chaos"
    return "Season & Legacy"


def _capability(key):
    return registry.CAPABILITY_REGISTRY.get(key)


def _difficulty_order(cap: dict, seed: str) -> list[str]:
    supported = set(cap.get("supported_difficulties") or ())
    # Reads should "go hard": prefer hard whenever that adapter has a real
    # certified hard band. Medium is the next fallback, then unfiltered any.
    order = []
    if "hard" in supported:
        order.append("hard")
    if "medium" in supported:
        order.append("medium")
    if "any" in supported:
        order.append("any")
    if "easy" in supported:
        order.append("easy")
    return order or ["any"]


def _generate_registered_question(seed: str, entry: tuple) -> dict | None:
    mechanic, domain, predicate, category, filters = entry
    key = (mechanic, domain, predicate)
    cap = _capability(key)
    if not cap:
        return None

    generate_fn = cap.get("generate_fn")
    if not callable(generate_fn):
        return None

    for difficulty in _difficulty_order(cap, seed):
        validated_spec = {
            "mechanic": mechanic,
            "domain": domain,
            "relationship_predicate": predicate,
            "question_count": 1,
            "difficulty": difficulty,
            "filters": dict(filters),
            "exclusions": [],
        }
        try:
            package = generate_fn(
                validated_spec,
                cap,
                request_text=f"Deep Ball shared pool: {category}",
                director_request_id="deep-ball-" + hashlib.sha256(seed.encode()).hexdigest()[:16],
                seed=seed,
                target_count=1,
                id_start=int(cap.get("pipeline_id_start") or 990000),
                freeze_timestamp=None,
            )
        except Exception:
            continue

        questions = package.get("questions") or []
        if not questions:
            continue
        q = questions[0]
        options = list(q.get("options") or [])
        correct_index = q.get("correctIndex")
        if not isinstance(correct_index, int) or not (0 <= correct_index < len(options)):
            continue
        if len(options) < 2:
            continue
        return {
            "category": category,
            "prompt": q["question"],
            "correct_label": options[correct_index],
            "decoy_labels": [label for i, label in enumerate(options) if i != correct_index],
            "notes": q.get("notes") or "Source-backed Reads Engine question.",
            "difficulty": q.get("difficulty") or difficulty.title(),
            "depth_source": f"{domain}/{predicate}",
            "bucket": _bucket_for(domain),
        }
    return None


def generate_rounds(seed: str, round_count: int) -> list[dict]:
    """Generate a diverse deterministic set of hard, source-backed rounds."""
    if round_count <= 0:
        return []

    rng = engine_bootstrap.seeded(seed + "-deep-pool")
    entries = list(_DEEP_CAPABILITIES)
    rng.shuffle(entries)

    rounds: list[dict] = []
    used_prompts: set[str] = set()
    used_categories: dict[str, int] = {}

    # Story Factory integration: reserve a bounded share for verified
    # story-backed questions. This shared pool feeds multiple arcade shells
    # (Wager, Category Roulette, Strategy Arcade), so one integration point
    # expands lore breadth across several games without duplicating logic.
    story_rounds = []
    try:
        c = engine_bootstrap.connect()
        try:
            # Strategy/arcade launch speed: verified READY_FOR_BANK story
            # MCQs are fetched in one indexed DB query, while each fallback
            # capability below invokes a full certified generation pipeline.
            # Fill up to two-thirds of the opening pool from the fast verified
            # source, then keep the remaining third for broader capability
            # diversity. This preserves depth without making a player wait on
            # 8-12 serial generation passes before the first screen.
            story_questions = load_story_mcqs(
                c,
                limit=max(1, min(round_count, (round_count * 2 + 2) // 3)),
            )
        finally:
            c.close()
        story_rounds = [to_deep_round(q) for q in story_questions]
        rng.shuffle(story_rounds)
    except Exception:
        story_rounds = []

    story_cap = max(1, min(len(story_rounds), (round_count * 2 + 2) // 3))
    for q in story_rounds[:story_cap]:
        if q["prompt"] in used_prompts:
            continue
        rounds.append(q)
        used_prompts.add(q["prompt"])
        used_categories[q["category"]] = used_categories.get(q["category"], 0) + 1
        if len(rounds) >= round_count:
            return rounds

    # Multiple passes let a capability produce a different deterministic
    # question when a format needs more rounds than there are capability
    # families, while still prioritizing breadth first.
    attempt = 0
    max_attempts = max(round_count * 8, len(entries) * 3)
    while len(rounds) < round_count and attempt < max_attempts:
        entry = entries[attempt % len(entries)]
        category = entry[3]
        # During the first breadth pass, don't let one family crowd out
        # unseen categories.
        if len(rounds) < min(round_count, MIN_DISTINCT_CATEGORIES_FOR_12) and used_categories.get(category, 0):
            attempt += 1
            continue

        q = _generate_registered_question(
            f"{seed}-deep-{attempt}-{entry[1]}-{entry[2]}", entry
        )
        attempt += 1
        if not q or q["prompt"] in used_prompts:
            continue
        used_prompts.add(q["prompt"])
        used_categories[category] = used_categories.get(category, 0) + 1
        rounds.append(q)

    return rounds



def generate_fast_arcade_rounds(seed: str, round_count: int) -> list[dict]:
    """Build a launch-safe mixed NFL/CFB pool without Director generation.

    Public Strategy Arcade modes need their first screen immediately. The
    normal Deep Ball generator intentionally runs full adapter/QA pipelines
    per question, which is excellent for authoring but too expensive on the
    production Fly volume for a synchronous tap-to-play path. This function
    uses only already-verified rows from the production warehouse plus
    READY_FOR_BANK story MCQs, all through one SQLite connection.

    The returned shape is identical to generate_rounds(), so Strategy Arcade
    keeps the same state machine/rendering and server-authoritative grading.
    """
    if round_count <= 0:
        return []

    rng = engine_bootstrap.seeded(seed + "-fast-arcade")
    rounds: list[dict] = []
    used_prompts: set[str] = set()

    c = engine_bootstrap.connect()
    try:
        # Synchronous tap-to-play must stay launch-safe. Story Factory rows
        # remain available to authoring/deeper pools, but the live arcade
        # opener intentionally starts from the lightweight certified tables
        # below so a slow story query can never block the first screen.
        # Fetch the three lightweight certified pools once. These tables are
        # already part of the Gateway's public safety contract elsewhere.
        try:
            heisman_rows = list(c.execute(
                "SELECT award_year,player_name,school_name "
                "FROM cfb_award_facts "
                "WHERE verification_status='SOURCE_BACKED_FROM_CFB_MASTER' "
                "AND award_name='Heisman Trophy' "
                "AND player_name IS NOT NULL AND school_name IS NOT NULL"
            ).fetchall())
        except Exception:
            heisman_rows = []

        try:
            playoff_rows = list(c.execute(
                "SELECT season,team_code,wins,losses,ties,playoff_result "
                "FROM season_standings "
                "WHERE verification_status='SOURCE_BACKED' "
                "AND source_id='NFLVERSE_DATA' "
                "AND playoff_result IS NOT NULL "
                "AND wins IS NOT NULL AND losses IS NOT NULL"
            ).fetchall())
        except Exception:
            playoff_rows = []

        try:
            champion_rows = list(c.execute(
                "SELECT season,winner_name_raw "
                "FROM nfl_championship_events "
                "WHERE verification_status='WIKIPEDIA_STRUCTURED_SECONDARY' "
                "AND winner_name_raw IS NOT NULL"
            ).fetchall())
        except Exception:
            # Older certified fixtures may not carry verification_status.
            try:
                champion_rows = list(c.execute(
                    "SELECT season,winner_name_raw FROM nfl_championship_events "
                    "WHERE winner_name_raw IS NOT NULL"
                ).fetchall())
            except Exception:
                champion_rows = []
    finally:
        c.close()

    rng.shuffle(heisman_rows)
    rng.shuffle(playoff_rows)
    rng.shuffle(champion_rows)

    def add_round(q: dict | None) -> None:
        if not q or q["prompt"] in used_prompts or len(rounds) >= round_count:
            return
        rounds.append(q)
        used_prompts.add(q["prompt"])

    # Build several distinct Heisman-school questions from one fetched list.
    school_names = sorted({str(r["school_name"]) for r in heisman_rows if r["school_name"]})
    for r in heisman_rows:
        correct = str(r["school_name"])
        decoys = [x for x in school_names if x != correct]
        if len(decoys) < 3:
            break
        rng.shuffle(decoys)
        add_round({
            "category": "Heisman Winners",
            "prompt": f"Which school did {r['award_year']} Heisman winner {r['player_name']} play for?",
            "correct_label": correct,
            "decoy_labels": decoys[:3],
            "notes": f"Verified Heisman winner: {r['player_name']} — {correct}.",
            "difficulty": "Medium",
            "depth_source": "cfb_award_facts",
            "bucket": "College Chaos",
        })
        if len(rounds) >= round_count:
            return rounds

    # NFL postseason outcome questions use the closed, real outcome set, so
    # distractors never require another DB query or generation pass.
    outcome_labels = {
        "WonSB": "Won the Super Bowl",
        "LostSB": "Lost the Super Bowl",
        "LostCC": "Lost in the Conference Championship",
        "LostDV": "Lost in the Divisional Round",
        "LostWC": "Lost in the Wild Card Round",
    }
    for r in playoff_rows:
        code = str(r["playoff_result"] or "")
        correct = outcome_labels.get(code)
        if not correct:
            continue
        decoys = [label for key, label in outcome_labels.items() if key != code]
        rng.shuffle(decoys)
        ties = int(r["ties"] or 0)
        record = f"{r['wins']}-{r['losses']}" + (f"-{ties}" if ties else "")
        add_round({
            "category": "NFL Playoff History",
            "prompt": f"How did {r['team_code']} finish the {r['season']} NFL season?",
            "correct_label": correct,
            "decoy_labels": decoys[:3],
            "notes": f"{r['team_code']} finished {record} in {r['season']} and {correct.lower()}.",
            "difficulty": "Medium",
            "depth_source": "season_standings/playoff_result",
            "bucket": "Season & Legacy",
        })
        if len(rounds) >= round_count:
            return rounds

    # Super Bowl champion questions add another real NFL category from the
    # structured championship table, again with no per-question generation.
    winners = sorted({str(r["winner_name_raw"]) for r in champion_rows if r["winner_name_raw"]})
    for r in champion_rows:
        correct = str(r["winner_name_raw"])
        decoys = [x for x in winners if x != correct]
        if len(decoys) < 3:
            break
        rng.shuffle(decoys)
        add_round({
            "category": "Super Bowl Champions",
            "prompt": f"Which team won the Super Bowl following the {r['season']} NFL season?",
            "correct_label": correct,
            "decoy_labels": decoys[:3],
            "notes": f"Verified {r['season']} season Super Bowl champion: {correct}.",
            "difficulty": "Medium",
            "depth_source": "nfl_championship_events",
            "bucket": "Season & Legacy",
        })
        if len(rounds) >= round_count:
            return rounds

    return rounds

def capability_count() -> int:
    return len(_DEEP_CAPABILITIES)
